---

- name: Install load balancer packages
  package:
    name: "{{ payload }}"
    state: present
  tags:
    - lbs
    - haproxy

- name: Configure haproxy load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy
  tags:  
    - lbs 
    - haproxy

- name: Enable Haproxy
  service:
    name: "{{ payload }}"
    state: started
    enabled: true
  tags:
    - lbs 
    - haproxy

